import type { Category, District, State } from "./types"

export const CATEGORIES: Category[] = [
  { id: "1", name: "Medical", icon: "medical-bag" },
  { id: "2", name: "Food", icon: "food" },
  { id: "3", name: "Clothing", icon: "tshirt-crew" },
  { id: "4", name: "Electronics", icon: "television" },
  { id: "5", name: "Grocery", icon: "cart" },
  { id: "6", name: "Furniture", icon: "chair-rolling" },
  { id: "7", name: "Automobile", icon: "car" },
  { id: "8", name: "Education", icon: "school" },
  { id: "9", name: "Beauty", icon: "face-woman" },
  { id: "10", name: "Hardware", icon: "tools" },
  { id: "11", name: "Sports", icon: "basketball" },
  { id: "12", name: "Books", icon: "book" },
  { id: "13", name: "Jewelry", icon: "diamond-stone" },
  { id: "14", name: "Pharmacy", icon: "pharmacy" },
  { id: "15", name: "Restaurant", icon: "food-fork-drink" },
  { id: "16", name: "Services", icon: "handshake" },
  { id: "17", name: "Home Decor", icon: "home-variant" },
  { id: "18", name: "Stationery", icon: "pencil" },
  { id: "19", name: "Other", icon: "dots-horizontal" },
]

// States of India
export const STATES: State[] = [
  { id: "GJ", name: "Gujarat" },
  { id: "MH", name: "Maharashtra" },
  { id: "DL", name: "Delhi" },
  { id: "KA", name: "Karnataka" },
  { id: "TN", name: "Tamil Nadu" },
  { id: "AN", name: "Andaman and Nicobar Islands" },
  { id: "AP", name: "Andhra Pradesh" },
  { id: "AR", name: "Arunachal Pradesh" },
  { id: "AS", name: "Assam" },
  { id: "BR", name: "Bihar" },
  { id: "CH", name: "Chandigarh" },
  { id: "CG", name: "Chhattisgarh" },
  { id: "DN", name: "Dadra and Nagar Haveli and Daman and Diu" },
  { id: "GA", name: "Goa" },
  { id: "HR", name: "Haryana" },
  { id: "HP", name: "Himachal Pradesh" },
  { id: "JK", name: "Jammu and Kashmir" },
  { id: "JH", name: "Jharkhand" },
  { id: "KL", name: "Kerala" },
  { id: "LA", name: "Ladakh" },
  { id: "LD", name: "Lakshadweep" },
  { id: "MP", name: "Madhya Pradesh" },
  { id: "MN", name: "Manipur" },
  { id: "ML", name: "Meghalaya" },
  { id: "MZ", name: "Mizoram" },
  { id: "NL", name: "Nagaland" },
  { id: "OD", name: "Odisha" },
  { id: "PY", name: "Puducherry" },
  { id: "PB", name: "Punjab" },
  { id: "RJ", name: "Rajasthan" },
  { id: "SK", name: "Sikkim" },
  { id: "TS", name: "Telangana" },
  { id: "TR", name: "Tripura" },
  { id: "UP", name: "Uttar Pradesh" },
  { id: "UK", name: "Uttarakhand" },
  { id: "WB", name: "West Bengal" },
]

// Gujarat districts
export const GUJARAT_DISTRICTS: District[] = [
  { id: "1", name: "Ahmedabad", stateId: "GJ" },
  { id: "2", name: "Amreli", stateId: "GJ" },
  { id: "3", name: "Anand", stateId: "GJ" },
  { id: "4", name: "Aravalli", stateId: "GJ" },
  { id: "5", name: "Banaskantha", stateId: "GJ" },
  { id: "6", name: "Bharuch", stateId: "GJ" },
  { id: "7", name: "Bhavnagar", stateId: "GJ" },
  { id: "8", name: "Botad", stateId: "GJ" },
  { id: "9", name: "Chhota Udaipur", stateId: "GJ" },
  { id: "10", name: "Dahod", stateId: "GJ" },
  { id: "11", name: "Dang", stateId: "GJ" },
  { id: "12", name: "Devbhoomi Dwarka", stateId: "GJ" },
  { id: "13", name: "Gandhinagar", stateId: "GJ" },
  { id: "14", name: "Gir Somnath", stateId: "GJ" },
  { id: "15", name: "Jamnagar", stateId: "GJ" },
  { id: "16", name: "Junagadh", stateId: "GJ" },
  { id: "17", name: "Kheda", stateId: "GJ" },
  { id: "18", name: "Kutch", stateId: "GJ" },
  { id: "19", name: "Mahisagar", stateId: "GJ" },
  { id: "20", name: "Mehsana", stateId: "GJ" },
  { id: "21", name: "Morbi", stateId: "GJ" },
  { id: "22", name: "Narmada", stateId: "GJ" },
  { id: "23", name: "Navsari", stateId: "GJ" },
  { id: "24", name: "Panchmahal", stateId: "GJ" },
  { id: "25", name: "Patan", stateId: "GJ" },
  { id: "26", name: "Porbandar", stateId: "GJ" },
  { id: "27", name: "Rajkot", stateId: "GJ" },
  { id: "28", name: "Sabarkantha", stateId: "GJ" },
  { id: "29", name: "Surat", stateId: "GJ" },
  { id: "30", name: "Surendranagar", stateId: "GJ" },
  { id: "31", name: "Tapi", stateId: "GJ" },
  { id: "32", name: "Vadodara", stateId: "GJ" },
  { id: "33", name: "Valsad", stateId: "GJ" },
]

// Maharashtra districts
export const MAHARASHTRA_DISTRICTS: District[] = [
  { id: "35", name: "Ahmednagar", stateId: "MH" },
  { id: "36", name: "Akola", stateId: "MH" },
  { id: "37", name: "Amravati", stateId: "MH" },
  { id: "38", name: "Aurangabad", stateId: "MH" },
  { id: "39", name: "Beed", stateId: "MH" },
  { id: "40", name: "Bhandara", stateId: "MH" },
  { id: "41", name: "Buldhana", stateId: "MH" },
  { id: "42", name: "Chandrapur", stateId: "MH" },
  { id: "43", name: "Dhule", stateId: "MH" },
  { id: "44", name: "Gadchiroli", stateId: "MH" },
  { id: "45", name: "Gondiya", stateId: "MH" },
  { id: "46", name: "Hingoli", stateId: "MH" },
  { id: "47", name: "Jalgaon", stateId: "MH" },
  { id: "48", name: "Jalna", stateId: "MH" },
  { id: "49", name: "Kolhapur", stateId: "MH" },
  { id: "50", name: "Latur", stateId: "MH" },
  { id: "51", name: "Mumbai City", stateId: "MH" },
  { id: "52", name: "Mumbai Suburban", stateId: "MH" },
  { id: "53", name: "Nagpur", stateId: "MH" },
  { id: "54", name: "Nanded", stateId: "MH" },
  { id: "55", name: "Nandurbar", stateId: "MH" },
  { id: "56", name: "Nashik", stateId: "MH" },
  { id: "57", name: "Osmanabad", stateId: "MH" },
  { id: "58", name: "Palghar", stateId: "MH" },
  { id: "59", name: "Parbhani", stateId: "MH" },
  { id: "60", name: "Pune", stateId: "MH" },
  { id: "61", name: "Raigad", stateId: "MH" },
  { id: "62", name: "Ratnagiri", stateId: "MH" },
  { id: "63", name: "Sangli", stateId: "MH" },
  { id: "64", name: "Satara", stateId: "MH" },
  { id: "65", name: "Sindhudurg", stateId: "MH" },
  { id: "66", name: "Solapur", stateId: "MH" },
  { id: "67", name: "Thane", stateId: "MH" },
  { id: "68", name: "Wardha", stateId: "MH" },
  { id: "69", name: "Washim", stateId: "MH" },
  { id: "70", name: "Yavatmal", stateId: "MH" },
]

// Delhi districts
export const DELHI_DISTRICTS: District[] = [
  { id: "71", name: "New Delhi", stateId: "DL" },
  { id: "72", name: "North Delhi", stateId: "DL" },
  { id: "73", name: "South Delhi", stateId: "DL" },
  { id: "74", name: "East Delhi", stateId: "DL" },
  { id: "75", name: "West Delhi", stateId: "DL" },
  { id: "76", name: "Central Delhi", stateId: "DL" },
  { id: "77", name: "North East Delhi", stateId: "DL" },
  { id: "78", name: "North West Delhi", stateId: "DL" },
  { id: "79", name: "South East Delhi", stateId: "DL" },
  { id: "80", name: "South West Delhi", stateId: "DL" },
  { id: "81", name: "Shahdara", stateId: "DL" },
]

// Karnataka districts
export const KARNATAKA_DISTRICTS: District[] = [
  { id: "82", name: "Bagalkot", stateId: "KA" },
  { id: "83", name: "Bangalore Rural", stateId: "KA" },
  { id: "84", name: "Bangalore Urban", stateId: "KA" },
  { id: "85", name: "Belgaum", stateId: "KA" },
  { id: "86", name: "Bellary", stateId: "KA" },
  { id: "87", name: "Bidar", stateId: "KA" },
  { id: "88", name: "Bijapur", stateId: "KA" },
  { id: "89", name: "Chamarajanagar", stateId: "KA" },
  { id: "90", name: "Chikkaballapur", stateId: "KA" },
  { id: "91", name: "Chikkamagaluru", stateId: "KA" },
  { id: "92", name: "Chitradurga", stateId: "KA" },
  { id: "93", name: "Dakshina Kannada", stateId: "KA" },
  { id: "94", name: "Dharwad", stateId: "KA" },
  { id: "95", name: "Gulbarga", stateId: "KA" },
  { id: "96", name: "Hassan", stateId: "KA" },
  { id: "97", name: "Kodagu", stateId: "KA" },
  { id: "98", name: "Kolar", stateId: "KA" },
  { id: "99", name: "Koppal", stateId: "KA" },
  { id: "100", name: "Mandya", stateId: "KA" },
  { id: "101", name: "Mysore", stateId: "KA" },
  { id: "102", name: "Raichur", stateId: "KA" },
  { id: "103", name: "Ramanagara", stateId: "KA" },
  { id: "104", name: "Shimoga", stateId: "KA" },
  { id: "105", name: "Siddharthnagar", stateId: "KA" },
  { id: "106", name: "Tumkur", stateId: "KA" },
  { id: "107", name: "Udupi", stateId: "KA" },
  { id: "108", name: "Yadgir", stateId: "KA" },
]

// Tamil Nadu districts
export const TAMIL_NADU_DISTRICTS: District[] = [
  { id: "109", name: "Ariyalur", stateId: "TN" },
  { id: "110", name: "Chengalpattu", stateId: "TN" },
  { id: "111", name: "Chennai", stateId: "TN" },
  { id: "112", name: "Coimbatore", stateId: "TN" },
  { id: "113", name: "Cuddalore", stateId: "TN" },
  { id: "114", name: "Dharmapuri", stateId: "TN" },
  { id: "115", name: "Dindigul", stateId: "TN" },
  { id: "116", name: "Erode", stateId: "TN" },
  { id: "117", name: "Kanniyakumari", stateId: "TN" },
  { id: "118", name: "Karur", stateId: "TN" },
  { id: "119", name: "Kancheepuram", stateId: "TN" },
  { id: "120", name: "Krishnagiri", stateId: "TN" },
  { id: "121", name: "Madurai", stateId: "TN" },
  { id: "122", name: "Mayiladuthurai", stateId: "TN" },
  { id: "123", name: "Nagapattinam", stateId: "TN" },
  { id: "124", name: "Namakkal", stateId: "TN" },
  { id: "125", name: "Nilgiris", stateId: "TN" },
  { id: "126", name: "Perambalur", stateId: "TN" },
  { id: "127", name: "Pudukkottai", stateId: "TN" },
  { id: "128", name: "Ramanathapuram", stateId: "TN" },
  { id: "129", name: "Ranipet", stateId: "TN" },
  { id: "130", name: "Salem", stateId: "TN" },
  { id: "131", name: "Sivaganga", stateId: "TN" },
  { id: "132", name: "Tenkasi", stateId: "TN" },
  { id: "133", name: "Thanjavur", stateId: "TN" },
  { id: "134", name: "Theni", stateId: "TN" },
  { id: "135", name: "Thiruvallur", stateId: "TN" },
  { id: "136", name: "Thoothukudi", stateId: "TN" },
  { id: "137", name: "Tiruchirappalli", stateId: "TN" },
  { id: "138", name: "Tirunelveli", stateId: "TN" },
  { id: "139", name: "Tirupattur", stateId: "TN" },
  { id: "140", name: "Tiruppur", stateId: "TN" },
  { id: "141", name: "Tiruvannamalai", stateId: "TN" },
  { id: "142", name: "Tiruvarur", stateId: "TN" },
  { id: "143", name: "Vellore", stateId: "TN" },
  { id: "144", name: "Viluppuram", stateId: "TN" },
  { id: "145", name: "Virudhunagar", stateId: "TN" },
]

// Andaman and Nicobar Islands districts
export const ANDAMAN_NICOBAR_DISTRICTS: District[] = [
  { id: "146", name: "Nicobar", stateId: "AN" },
  { id: "147", name: "North and Middle Andaman", stateId: "AN" },
  { id: "148", name: "South Andaman", stateId: "AN" },
]

// Andhra Pradesh districts
export const ANDHRA_PRADESH_DISTRICTS: District[] = [
  { id: "149", name: "Alluri Sitharama Raju", stateId: "AP" },
  { id: "150", name: "Anantapur", stateId: "AP" },
  { id: "151", name: "Annamayya", stateId: "AP" },
  { id: "152", name: "Bapatla", stateId: "AP" },
  { id: "153", name: "Chittoor", stateId: "AP" },
  { id: "154", name: "Dr. B.R. Ambedkar Konaseema", stateId: "AP" },
  { id: "155", name: "East Godavari", stateId: "AP" },
  { id: "156", name: "Eluru", stateId: "AP" },
  { id: "157", name: "Guntur", stateId: "AP" },
  { id: "158", name: "Kakinada", stateId: "AP" },
  { id: "159", name: "Krishna", stateId: "AP" },
  { id: "160", name: "Kurnool", stateId: "AP" },
  { id: "161", name: "Nandyal", stateId: "AP" },
  { id: "162", name: "Nellore", stateId: "AP" },
  { id: "163", name: "NTR", stateId: "AP" },
  { id: "164", name: "Palnadu", stateId: "AP" },
  { id: "165", name: "Parvathipuram Manyam", stateId: "AP" },
  { id: "166", name: "Prakasam", stateId: "AP" },
  { id: "167", name: "Sri Potti Sriramulu Nellore", stateId: "AP" },
  { id: "168", name: "Sri Sathya Sai", stateId: "AP" },
  { id: "169", name: "Srikakulam", stateId: "AP" },
  { id: "170", name: "Tirupati", stateId: "AP" },
  { id: "171", name: "Visakhapatnam", stateId: "AP" },
  { id: "172", name: "Vizianagaram", stateId: "AP" },
  { id: "173", name: "West Godavari", stateId: "AP" },
  { id: "174", name: "YSR Kadapa", stateId: "AP" },
]

// Arunachal Pradesh districts
export const ARUNACHAL_PRADESH_DISTRICTS: District[] = [
  { id: "175", name: "Anjaw", stateId: "AR" },
  { id: "176", name: "Bichom", stateId: "AR" },
  { id: "177", name: "Changlang", stateId: "AR" },
  { id: "178", name: "Dibang Valley", stateId: "AR" },
  { id: "179", name: "East Kameng", stateId: "AR" },
  { id: "180", name: "East Siang", stateId: "AR" },
  { id: "181", name: "Itanagar", stateId: "AR" },
  { id: "182", name: "Kamle", stateId: "AR" },
  { id: "183", name: "Kra Daadi", stateId: "AR" },
  { id: "184", name: "Kurung Kumey", stateId: "AR" },
  { id: "185", name: "Lepa-Rada", stateId: "AR" },
  { id: "186", name: "Lohit", stateId: "AR" },
  { id: "187", name: "Longding", stateId: "AR" },
  { id: "188", name: "Lower Dibang Valley", stateId: "AR" },
  { id: "189", name: "Lower Subansiri", stateId: "AR" },
  { id: "190", name: "Namsai", stateId: "AR" },
  { id: "191", name: "Papum Pare", stateId: "AR" },
  { id: "192", name: "Shi Yomi", stateId: "AR" },
  { id: "193", name: "Siang", stateId: "AR" },
  { id: "194", name: "Tawang", stateId: "AR" },
  { id: "195", name: "Tirap", stateId: "AR" },
  { id: "196", name: "Upper Siang", stateId: "AR" },
  { id: "197", name: "Upper Subansiri", stateId: "AR" },
  { id: "198", name: "West Kameng", stateId: "AR" },
  { id: "199", name: "West Siang", stateId: "AR" },
]

// Assam districts
export const ASSAM_DISTRICTS: District[] = [
  { id: "200", name: "Bajali", stateId: "AS" },
  { id: "201", name: "Baksa", stateId: "AS" },
  { id: "202", name: "Barpeta", stateId: "AS" },
  { id: "203", name: "Biswanath", stateId: "AS" },
  { id: "204", name: "Bongaigaon", stateId: "AS" },
  { id: "205", name: "Cachar", stateId: "AS" },
  { id: "206", name: "Charaideo", stateId: "AS" },
  { id: "207", name: "Chirang", stateId: "AS" },
  { id: "208", name: "Darrang", stateId: "AS" },
  { id: "209", name: "Dhemaji", stateId: "AS" },
  { id: "210", name: "Dhubri", stateId: "AS" },
  { id: "211", name: "Dibrugarh", stateId: "AS" },
  { id: "212", name: "Dima Hasao", stateId: "AS" },
  { id: "213", name: "Goalpara", stateId: "AS" },
  { id: "214", name: "Golaghat", stateId: "AS" },
  { id: "215", name: "Hailakandi", stateId: "AS" },
  { id: "216", name: "Hojai", stateId: "AS" },
  { id: "217", name: "Jorhat", stateId: "AS" },
  { id: "218", name: "Kamrup", stateId: "AS" },
  { id: "219", name: "Kamrup Metropolitan", stateId: "AS" },
  { id: "220", name: "Karbi Anglong", stateId: "AS" },
  { id: "221", name: "Karimganj", stateId: "AS" },
  { id: "222", name: "Kokrajhar", stateId: "AS" },
  { id: "223", name: "Lakhimpur", stateId: "AS" },
  { id: "224", name: "Majuli", stateId: "AS" },
  { id: "225", name: "Morigaon", stateId: "AS" },
  { id: "226", name: "Nagaon", stateId: "AS" },
  { id: "227", name: "Nalbari", stateId: "AS" },
  { id: "228", name: "Sivasagar", stateId: "AS" },
  { id: "229", name: "Sonitpur", stateId: "AS" },
  { id: "230", name: "South Salmara-Mankachar", stateId: "AS" },
  { id: "231", name: "Tamulpur", stateId: "AS" },
  { id: "232", name: "Tinsukia", stateId: "AS" },
  { id: "233", name: "Udalguri", stateId: "AS" },
  { id: "234", name: "West Karbi Anglong", stateId: "AS" },
]

// Bihar districts
export const BIHAR_DISTRICTS: District[] = [
  { id: "235", name: "Araria", stateId: "BR" },
  { id: "236", name: "Arwal", stateId: "BR" },
  { id: "237", name: "Aurangabad", stateId: "BR" },
  { id: "238", name: "Banka", stateId: "BR" },
  { id: "239", name: "Begusarai", stateId: "BR" },
  { id: "240", name: "Bhagalpur", stateId: "BR" },
  { id: "241", name: "Bhojpur", stateId: "BR" },
  { id: "242", name: "Buxar", stateId: "BR" },
  { id: "243", name: "Darbhanga", stateId: "BR" },
  { id: "244", name: "East Champaran", stateId: "BR" },
  { id: "245", name: "Gaya", stateId: "BR" },
  { id: "246", name: "Gopalganj", stateId: "BR" },
  { id: "247", name: "Jamui", stateId: "BR" },
  { id: "248", name: "Jehanabad", stateId: "BR" },
  { id: "249", name: "Kaimur (Bhabua)", stateId: "BR" },
  { id: "250", name: "Katihar", stateId: "BR" },
  { id: "251", name: "Khagaria", stateId: "BR" },
  { id: "252", name: "Kishanganj", stateId: "BR" },
  { id: "253", name: "Lakhisarai", stateId: "BR" },
  { id: "254", name: "Madhepura", stateId: "BR" },
  { id: "255", name: "Madhubani", stateId: "BR" },
  { id: "256", name: "Munger", stateId: "BR" },
  { id: "257", name: "Muzaffarpur", stateId: "BR" },
  { id: "258", name: "Nalanda", stateId: "BR" },
  { id: "259", name: "Nawada", stateId: "BR" },
  { id: "260", name: "Patna", stateId: "BR" },
  { id: "261", name: "Pashchim Champaran", stateId: "BR" },
  { id: "262", name: "Purnia", stateId: "BR" },
  { id: "263", name: "Rohtas", stateId: "BR" },
  { id: "264", name: "Saharsa", stateId: "BR" },
  { id: "265", name: "Samastipur", stateId: "BR" },
  { id: "266", name: "Sheikhpura", stateId: "BR" },
  { id: "267", name: "Sheohar", stateId: "BR" },
  { id: "268", name: "Sitamarhi", stateId: "BR" },
  { id: "269", name: "Siwan", stateId: "BR" },
  { id: "270", name: "Supaul", stateId: "BR" },
  { id: "271", name: "Vaishali", stateId: "BR" },
  { id: "272", name: "West Champaran", stateId: "BR" },
]

// All other district arrays would be added here similarly...

// Combine all districts
export const ALL_DISTRICTS: District[] = [
  ...GUJARAT_DISTRICTS,
  ...MAHARASHTRA_DISTRICTS,
  ...DELHI_DISTRICTS,
  ...KARNATAKA_DISTRICTS,
  ...TAMIL_NADU_DISTRICTS,
  ...ANDAMAN_NICOBAR_DISTRICTS,
  ...ANDHRA_PRADESH_DISTRICTS,
  ...ARUNACHAL_PRADESH_DISTRICTS,
  ...ASSAM_DISTRICTS,
  ...BIHAR_DISTRICTS,
  // Add other district arrays as needed
]

// For backward compatibility, keep DISTRICTS array with same districts as before
export const DISTRICTS = GUJARAT_DISTRICTS

// Admin credentials (in real app, this would be in a secure backend)
export const ADMIN_CREDENTIALS = {
  username: "Ayan9923",
  password: "Ayan1102",
}

